version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: 
      always
    ports:
    - "27017:27017"
    volumes:
    - mongo_data:/data/db

  orderdb:
    container_name: orderdb
    restart: 
      always
    ports:
    - "1433:1433"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - orderdb
    ports:
      - "8001:80"
